#!/bin/bash

git  add .

git commit -m "cambio con script"

git config --global user.name "Mona Lisa"

git config --global user.passworsd "Mona Lisa"

git push --set-upstream https://github.com/sergionet17/demo-integration-services  master



